/**
 * Regenerates the governance-facing spec snapshots under specs/ from the
 * canonical TypeScript definitions in supabase/functions/_shared/. Run this
 * after editing a profile or the validator catalogue so the committed JSON
 * artifacts (what a human reviewer or a downstream tool would read) stay in
 * sync with the code that actually runs.
 *
 * Usage: npx tsx scripts/export-specs.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { ALL_PROFILES, expandRepeatingFieldPaths } from "../../../supabase/functions/_shared/profiles/index.ts";
import { ALL_VALIDATORS } from "../../../supabase/functions/_shared/validation/index.ts";
import type { DocumentProfileDefinition, ProfileFieldDefinition } from "../../../supabase/functions/_shared/profiles/types.ts";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");

function jsonSchemaTypeFor(type: ProfileFieldDefinition["type"]): unknown {
  switch (type) {
    case "string":
    case "date":
      return { type: "string" };
    case "number":
      return { type: "number" };
    case "boolean":
      return { type: "boolean" };
    case "array":
      return { type: "array", items: { type: "string" } };
    case "object":
      return { type: "object" };
  }
}

/** Derive a documentation-only JSON Schema (2020-12) from a profile's field catalogue. */
function profileToJsonSchema(profile: DocumentProfileDefinition) {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  for (const f of profile.fields) {
    properties[f.path] = { ...(jsonSchemaTypeFor(f.type) as object), description: f.description };
    if (f.required) required.push(f.path);
  }
  if (profile.repeatingGroup) {
    const itemProps: Record<string, unknown> = {};
    const itemRequired: string[] = [];
    for (const f of profile.repeatingGroup.fields) {
      const leafName = f.path.replace(`${profile.repeatingGroup.groupPath}[{i}].`, "");
      itemProps[leafName] = { ...(jsonSchemaTypeFor(f.type) as object), description: f.description };
      if (f.required) itemRequired.push(leafName);
    }
    properties[profile.repeatingGroup.groupPath] = {
      type: "array",
      description: `Repeating group — any number of rows, including zero.`,
      items: { type: "object", properties: itemProps, required: itemRequired },
    };
  }
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: `${profile.title} — field catalogue (documentation snapshot)`,
    description: `Generated from supabase/functions/_shared/profiles/${profile.id === "commercial_invoice" ? "commercial-invoice" : profile.id}.ts by scripts/export-specs.ts. This documents the field catalogue; the actual extraction tool schema Claude fills in is the generic FieldResultDraft[] shape shared across all profiles (see supabase/functions/_shared/envelope-types.ts) — do not treat this file as the literal tool input_schema.`,
    type: "object",
    properties,
    required,
  };
}

function profileSnapshot(profile: DocumentProfileDefinition) {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    artifact_id: `M5-PROFILE-${profile.id.toUpperCase()}-001`,
    status: `${profile.status} — awaiting Phase 0 gate and Engineering Lead / Domain Reviewer sign-off`,
    id: profile.id,
    version: profile.version,
    title: profile.title,
    description: profile.description,
    fields: profile.fields,
    repeating_group: profile.repeatingGroup,
    validator_ids: profile.validatorIds,
    extraction_prompt: profile.extractionPrompt,
    field_catalogue_json_schema: profileToJsonSchema(profile),
  };
}

for (const profile of ALL_PROFILES) {
  const filename = profile.id === "commercial_invoice" ? "commercial-invoice" : profile.id;
  const outPath = path.join(root, "specs", "profiles", `${filename}-v0.1-PROPOSED.json`);
  writeFileSync(outPath, JSON.stringify(profileSnapshot(profile), null, 2) + "\n", "utf8");
  console.log(`wrote ${path.relative(root, outPath)}`);
  // Exercise the repeating-group expansion once so a schema mistake in the
  // template ({i} placeholder etc.) surfaces here rather than only at runtime.
  void expandRepeatingFieldPaths(profile, 2);
}

const catalogue = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  artifact_id: "M5-VALIDATOR-CATALOGUE-001",
  status: "PROPOSED — awaiting Phase 0 gate and Engineering Lead / Domain Reviewer sign-off",
  description:
    "Deterministic validator catalogue. Runs independently of the model (Charter/Task Protocol requirement) — see supabase/functions/_shared/validation/*.ts. Generated by scripts/export-specs.ts.",
  validators: ALL_VALIDATORS.map((v) => ({
    id: v.id,
    category: v.category,
    title: v.title,
    description: v.description,
  })),
};
const catalogueOut = path.join(root, "specs", "validator-catalogue-v0.1-PROPOSED.json");
writeFileSync(catalogueOut, JSON.stringify(catalogue, null, 2) + "\n", "utf8");
console.log(`wrote ${path.relative(root, catalogueOut)}`);
