#!/usr/bin/env node
// Vendors the design system into one or more apps. Plain Node (no deps, no tsx/ts-node)
// so it never breaks a fresh `npm install` the way M5's old postinstall script once did
// (see M5's docs/lovable-handoff-runbook.md §1b).
//
// WHY THIS EXISTS: apps/* must each stay a flat, standalone Vite project — no pnpm
// workspace, no `workspace:*` protocol — so any one of them can be dropped into Lovable
// directly, exactly like the M5 Document Intelligence module was (ADR-012: this stack was
// chosen specifically because it matches what Lovable generates and imports cleanly).
// packages/tokens and packages/ui are therefore never installed as npm dependencies; they
// are the authored source, and this script copies (vendors) that source into each app's
// own src/ tree, the same way `npx shadcn add` copies a component into your repo instead
// of installing a UI library.
//
// Usage:
//   node scripts/sync-ui.mjs shell
//   node scripts/sync-ui.mjs --all
//
// Re-run this after editing anything in packages/tokens/src or packages/ui/src. It always
// overwrites: src/components/ui/*, src/components/oravio/*, src/lib/utils.ts,
// src/oravio-preset.ts, and src/index.css. It never touches tailwind.config.ts,
// components.json, index.html, package.json, or vite.config.ts — those are per-app
// scaffold files created once (see apps/_template) and are expected to diverge slightly
// per app (different content globs, different app name).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const APPS_DIR = path.join(ROOT, "apps");
const UI_SRC = path.join(ROOT, "packages", "ui", "src");
const TOKENS_SRC = path.join(ROOT, "packages", "tokens", "src");
const AUTH_SRC = path.join(ROOT, "packages", "auth", "src");
const ENTITLEMENTS_SRC = path.join(ROOT, "packages", "entitlements", "src");

function copyDir(srcDir, destDir) {
  fs.mkdirSync(destDir, { recursive: true });
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    if (entry.name.includes("__parity__") || entry.name.endsWith(".test.ts")) continue;
    const srcPath = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);
    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function generateIndexCss(appDir) {
  const tokens = fs.readFileSync(path.join(TOKENS_SRC, "tokens.css"), "utf8");
  const indented = tokens
    .split("\n")
    .map((line) => (line.length ? "  " + line : line))
    .join("\n");
  const out = `@tailwind base;
@tailwind components;
@tailwind utilities;

/*
 * GENERATED by scripts/sync-ui.mjs from packages/tokens/src/tokens.css — do not hand-edit.
 * Edit the source in packages/tokens/src/tokens.css and re-run:
 *   node scripts/sync-ui.mjs <appName>
 */

@layer base {
${indented}
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground antialiased;
    font-family: var(--font-sans);
  }
}
`;
  fs.writeFileSync(path.join(appDir, "src", "index.css"), out);
}

function syncApp(appName) {
  const appDir = path.join(APPS_DIR, appName);
  if (!fs.existsSync(appDir)) {
    console.error(`No such app: ${appName} (looked in ${appDir})`);
    process.exitCode = 1;
    return;
  }

  copyDir(path.join(UI_SRC, "primitives"), path.join(appDir, "src", "components", "ui"));
  copyDir(path.join(UI_SRC, "oravio"), path.join(appDir, "src", "components", "oravio"));
  fs.mkdirSync(path.join(appDir, "src", "lib"), { recursive: true });
  fs.copyFileSync(
    path.join(UI_SRC, "lib", "utils.ts"),
    path.join(appDir, "src", "lib", "utils.ts"),
  );
  fs.copyFileSync(
    path.join(TOKENS_SRC, "tailwind-preset.ts"),
    path.join(appDir, "src", "oravio-preset.ts"),
  );
  generateIndexCss(appDir);

  // auth/entitlements source trees mirror their final vendor path 1:1 (e.g.
  // packages/auth/src/lib/auth/* -> src/lib/auth/*), so copying the whole subtree onto
  // the app's src/ merges cleanly without touching sibling files like src/lib/utils.ts.
  copyDir(AUTH_SRC, path.join(appDir, "src"));
  copyDir(ENTITLEMENTS_SRC, path.join(appDir, "src"));

  console.log(`Synced design system into apps/${appName}`);
}

const args = process.argv.slice(2);
if (args[0] === "--all") {
  for (const name of fs.readdirSync(APPS_DIR)) {
    if (fs.existsSync(path.join(APPS_DIR, name, "src"))) syncApp(name);
  }
} else if (args[0]) {
  syncApp(args[0]);
} else {
  console.error("Usage: node scripts/sync-ui.mjs <appName> | --all");
  process.exitCode = 1;
}
